### ISSUE TITLE
Incorrect change

### ISSUE THREAD

**Issue by maxday** [lo-enterprise/bkp-enterprise#1]
Hi,

Here is my scenario
- One call to /api/coins with the following body
  [{ "amount": 1, "quantity": 1 },{ "amount": 2, "quantity": 1 }, { "amount": 3, "quantity": 1 },{ "amount": 4, "quantity": 1 },{ "amount": 5, "quantity": 1 }]
- The exact same call, a second time
- Here, in the machine, there are 
  - 2 coins of 1
  - 2 coins of 2
  - 2 coins of 3
  - 2 coins of 4
  - 2 coins of 5
- Let's ask the change for 12 by calling /api/CoinChanges with the following body
  {"amount":12}

-> retrieved id = 1
- Finally let's fetch the result by calling api/CoinChanges/1/coins

The result is 1 coin of 1, 1 coin of 2, 1 coin of 4, 1coin of 5. (4 coins)

This doesn't maximize the number of coins.
A better solution is 2 coins of 1, 2coins of 2, 2coins of 3. (6coins)

**Comment by lo-enterprise** [comment]
Hi, 

Thanks for your feed back.
This problem has been fixed yesterday night. 

Now the knapsack resolution is performed on a sorted list of coins. c.f. cca801a
Consequently the first  [best](https://github.com/lo-enterprise/bkp/blob/master/index.js#L41) that is returned is the one corresponding to our problem (The maximum number of coin with the lower amount that match requested amount).

**Comment by lo-enterprise** [comment]
You test case is strange. Because if these coins are inserted:
- 1 coins of 1
- 1 coins of 2
- 1 coins of 3
- 1 coins of 4
- 1 coins of 5

Coin change for 12 returns:
`
[
  {
    "amount": 1,
    "quantity": -1,
    "id": 6,
    "coinId": 1,
    "coinChangeId": 1
  },
  {
    "amount": 2,
    "quantity": -1,
    "id": 7,
    "coinId": 2,
    "coinChangeId": 1
  },
  {
    "amount": 4,
    "quantity": -1,
    "id": 8,
    "coinId": 4,
    "coinChangeId": 1
  },
  {
    "amount": 5,
    "quantity": -1,
    "id": 9,
    "coinId": 5,
    "coinChangeId": 1
  }
]
`

**Comment by lo-enterprise** [comment]
Please provide detailed test scenario with curl command if you are able to reproduce you issue with last version of project.

**Comment by AlexandreGarino** [comment]
Hi Max,

I did the same test you did and that works like a charm.
1. Add the first coin set:

```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "
[{ \"amount\": 1, \"quantity\": 1 },
    { \"amount\": 2, \"quantity\": 1 },
    { \"amount\": 3, \"quantity\": 1 },  
    { \"amount\": 4, \"quantity\": 1 }, 
    { \"amount\": 5, \"quantity\": 1 } 
]" "http://localhost:3000/api/Coins"
```
1. Add the second coin set (the same as previous):

```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "
[{ \"amount\": 1, \"quantity\": 1 },
    { \"amount\": 2, \"quantity\": 1 },
    { \"amount\": 3, \"quantity\": 1 },  
    { \"amount\": 4, \"quantity\": 1 }, 
    { \"amount\": 5, \"quantity\": 1 } 
]" "http://localhost:3000/api/Coins"
```
1. Make the change:

```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"amount\": 12
}" "http://localhost:3000/api/CoinChanges"
```

```
{"amount":12,"id":1}
```
1. Get the change details:

```
curl -X GET --header "Accept: application/json" "http://localhost:3000/api/CoinChanges/1/coins"
```

```
[{"amount":1,"quantity":-1,"id":11,"coinId":1,"coinChangeId":1},{"amount":1,"quantity":-1,"id":12,"coinId":6,"coinChangeId":1},{"amount":2,"quantity":-1,"id":13,"coinId":2,"coinChangeId":1},{"amount":2,"quantity":-1,"id":14,"coinId":7,"coinChangeId":1},{"amount":3,"quantity":-1,"id":15,"coinId":3,"coinChangeId":1},{"amount":3,"quantity":-1,"id":16,"coinId":8,"coinChangeId":1}]
```

The result is 2 coins of 1, 2 coins of 2 and 2 coins of 3 which is the optimal result.

Make sure your code base is up-to-date.

Cheers,
Alexandre
